NUMPY


In [1]:
import numpy as np

In [6]:
lst=[1,2,3,4]

In [7]:
np.array(lst)

array([1, 2, 3, 4])

In [8]:
lst2 = [[1,2,3],[4,5,6,],[7,8,9,]]

In [9]:
np.array(lst2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11,1)  #arange function is used to make a 1d matrix wid element widin the defined range of defined interval

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,100,7.4)

array([ 1. ,  8.4, 15.8, 23.2, 30.6, 38. , 45.4, 52.8, 60.2, 67.6, 75. ,
       82.4, 89.8, 97.2])

In [12]:
np.zeros(10)    #make a zero matix

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:

np.ones(9)  #makes a mtrix wid all element 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.linspace(1,11,5)   #it will  create the matrix wid no. of element defined in defined range of equal interval

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [18]:
np.arange(1,11,5)

array([1, 6])

In [19]:
np.eye(4)         #it will create the identity matrix of defined rows and column

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(5,6)  #will use the interval from 0 to 1

array([[0.40023236, 0.86182201, 0.54793215, 0.58799504, 0.27151016,
        0.7321856 ],
       [0.41262959, 0.39438912, 0.50468295, 0.43476718, 0.14506567,
        0.55014355],
       [0.04138249, 0.52189756, 0.48312803, 0.48854798, 0.78865892,
        0.560421  ],
       [0.52504393, 0.21487897, 0.48532689, 0.52561396, 0.41305059,
        0.45984168],
       [0.72559692, 0.36149874, 0.76600484, 0.77861982, 0.7156355 ,
        0.97064693]])

In [28]:
np.random.randn(5,6)  #difference between rand and random ia that rand perform on uniform distribution of values whie randn is for normal distribution of number

array([[ 6.42528361e-01, -1.39490935e+00, -6.86465297e-01,
        -7.55509543e-01, -4.37473057e-01, -6.17278505e-02],
       [-1.13306392e-01,  1.58775551e-01,  4.47675687e-01,
         1.09258668e+00,  2.04889500e+00,  2.08361135e+00],
       [-1.05381798e-01,  9.86527953e-01, -7.89305418e-04,
        -1.65602107e+00, -1.80765707e-02, -1.54107543e+00],
       [-1.30762593e-01,  4.53769887e-01, -7.94017119e-01,
         2.05735037e-01,  1.03177967e+00, -1.46914461e-01],
       [ 6.20152586e-01, -3.29931593e-02, -7.19345254e-01,
        -9.94276676e-01,  4.31784664e-01, -2.70372906e-01]])

In [1]:
import numpy as np
np.random.randint(5,40,5) #randint chooses the random interger from range that is defined under function

array([27, 18, 10, 10, 30])

In [2]:
np.random.randint(1,100,20)

array([30, 50, 41, 36,  1, 13, 64, 80, 17, 28, 28, 91, 20, 66, 28, 88, 35,
       82, 12, 76])

In [5]:
import numpy as np

In [8]:
 np.random.randint(1,100,20)

array([97, 87, 48, 39, 34,  3, 94, 41, 84, 16,  8, 88, 20, 89, 43,  4, 58,
       17, 88, 67])

In [ ]:
import numpy as np

In [6]:
import numpy as np
arr1= np.random.rand(2,3,)
print(arr1)

[[0.6868783  0.16788423 0.33270018]
 [0.8767478  0.72417795 0.72781826]]


In [7]:
arr1.max()   #gives the maximum value

0.8767477969950401

In [8]:
arr1.argmax() #gives the position of max value

3

In [9]:
arr1.max()  #gives the minimum value

0.8767477969950401

In [11]:
arr1.shape  #gives the shape of matrix

(2, 3)

In [12]:
arr1.reshape(3,2)  #reshape is used to make the matrix of desiered shape but point to note is that it will work only if reshaping of elemet of desured matrix is possible (we can use the logic that mxn=no.of element)

array([[0.6868783 , 0.16788423],
       [0.33270018, 0.8767478 ],
       [0.72417795, 0.72781826]])

In [13]:
arr1.reshape(6,1)

array([[0.6868783 ],
       [0.16788423],
       [0.33270018],
       [0.8767478 ],
       [0.72417795],
       [0.72781826]])

In [21]:
a = arr1.reshape(1,6)
print(a)

[[0.6868783  0.16788423 0.33270018 0.8767478  0.72417795 0.72781826]]


In [22]:
a.dtype   #dtype is used to know the datatype of element of the matrix

dtype('float64')

In [23]:
a.T    #usw to transpose the matrix

array([[0.6868783 ],
       [0.16788423],
       [0.33270018],
       [0.8767478 ],
       [0.72417795],
       [0.72781826]])

In [24]:
arr1.T

array([[0.6868783 , 0.8767478 ],
       [0.16788423, 0.72417795],
       [0.33270018, 0.72781826]])

In [49]:
arr2 = np.arange(1,20,2)
print(arr2)

[ 1  3  5  7  9 11 13 15 17 19]


indexing and slicing 1d array

In [35]:
arr2[5]    #give the value present at given index(indexing starts from zero)

11

In [36]:
arr2[3:8]  #slicing the array(last point is exclusive)


array([ 7,  9, 11, 13, 15])

In [38]:
arr2[:]= 4  #broadcasting of all the values to a particular value

In [39]:
arr2

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [45]:
arr2[:]= 5
arr2


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [43]:
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [47]:
arr3= arr2.copy() #copy function create the copy of an array
arr3

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

indexing matrix

In [5]:
mat1=np.array(([1,3,3,3],[2,3,4,5],[3,4,5,6]))
mat1

array([[1, 3, 3, 3],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [6]:
mat1[1][3] #indexing of matrix

5

In [9]:
mat1[2,3] #always remember indexing starts from zero for both row and column

6

In [10]:
mat1[2:]  #slicing the array

array([[3, 4, 5, 6]])

In [12]:
mat1[0:2]

array([[1, 3, 3, 3],
       [2, 3, 4, 5]])

In [3]:
mat2= np.arange(1,30)
mat2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
mat2>6 #gives boolean output value

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [12]:
mat2[mat2>6]  #get only the values which satisfies the condition

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29])

In [14]:
mat2+mat2   #direct addition of array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [4]:
mat3= np.arange(2,31)  

In [5]:
mat3

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [20]:
mat2+mat3

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59])

In [21]:
mat2-mat3   #matrix subtraction

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [23]:
mat2/mat3  #matrix divison

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      , 0.95238095,
       0.95454545, 0.95652174, 0.95833333, 0.96      , 0.96153846,
       0.96296296, 0.96428571, 0.96551724, 0.96666667])

In [27]:
np.multiply(mat2,mat3)   #matrix multipication

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110, 132, 156, 182,
       210, 240, 272, 306, 342, 380, 420, 462, 506, 552, 600, 650, 702,
       756, 812, 870])

In [28]:
3+mat2

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [29]:
3+mat2+mat3

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
       40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62])

In [6]:
np.sqrt(mat3) #finding square root of eah elemnt

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894, 4.47213595, 4.58257569,
       4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
       5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [7]:
np.log(mat3) #natural log of element

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527,
       2.48490665, 2.56494936, 2.63905733, 2.7080502 , 2.77258872,
       2.83321334, 2.89037176, 2.94443898, 2.99573227, 3.04452244,
       3.09104245, 3.13549422, 3.17805383, 3.21887582, 3.25809654,
       3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [8]:
np.exp(mat3)

array([7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
       4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
       2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08, 1.31881573e+09,
       3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
       1.95729609e+11, 5.32048241e+11, 1.44625706e+12, 3.93133430e+12,
       1.06864746e+13])

In [9]:
np.mean(mat3)  #finding mean of all the element

16.0

In [10]:
np.std(mat3)  #findind standard deviation of all the element

8.366600265340756

In [11]:
np.var(mat3)  #finding varience of alll the element

70.0

input output in numpy

In [2]:
mat4 = np.arange(1,34)

In [3]:
mat4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [4]:
np.save("mat4",mat4)  #save the file in homepage with npy extension

In [5]:
mat5 = np.arange(1,45)

In [6]:
mat5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [7]:
np.savez("mat4_mat5",mat4,mat5) #savez function is used to arrayof moe than 1 with npz extension

In [9]:
np.load("mat4_mat5.npz")

In [10]:
np.load("mat4.npy")       #load is used to load the file saves with save function

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])